# Generated by Django 6.0.1 on 2026-02-04 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Namber_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCar', models.CharField(default='Mersedes Bens', max_length=100)),
                ('number_car', models.CharField(default='...KG...', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Documentcar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100)),
                ('chois_car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='relation_db.namber_car')),
            ],
        ),
    ]
