<<<<<<< HEAD
# Generated by Django 6.0.1 on 2026-02-04 12:41
=======
# Generated by Django 6.0.1 on 2026-02-14 11:51
>>>>>>> 88e1fbe6 (Классные работы)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Namber_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCar', models.CharField(default='Mersedes Bens', max_length=100)),
                ('number_car', models.CharField(default='...KG...', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Documentcar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100)),
                ('chois_car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='relation_db.namber_car')),
            ],
        ),
=======
            name='NumberCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCar', models.CharField(default='Lexus GX 570', max_length=100)),
                ('nummer_car', models.CharField(default='..KG....', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100)),
                ('choice_car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='relation_db.numbercar')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=100)),
                ('text', models.CharField(default='отличная машина', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='relation_db.numbercar')),
            ],
        ),
        migrations.AddField(
            model_name='numbercar',
            name='tags',
            field=models.ManyToManyField(null=True, to='relation_db.tag'),
        ),
>>>>>>> 88e1fbe6 (Классные работы)
    ]
