# Generated by Django 6.0.1 on 2026-02-04 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=100)),
                ('number_car', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentcar',
            name='chois_car',
        ),
        migrations.AddField(
            model_name='documentcar',
            name='car',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='relation_db.numbercar'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Namber_car',
        ),
    ]
