# Generated by Django 6.0.1 on 2026-02-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0002_numbercar_remove_documentcar_chois_car_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentcar',
            old_name='car',
            new_name='машина',
        ),
    ]
