# Generated by Django 6.0.1 on 2026-02-04 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0003_rename_car_documentcar_машина'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcar',
            name='машина',
        ),
        migrations.AddField(
            model_name='documentcar',
            name='тех_паспортом',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='relation_db.numbercar'),
        ),
    ]
