# Generated by Django 6.0.1 on 2026-02-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0006_tag_numbercar_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbercar',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='review',
            name='chois_car',
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toure', models.CharField(max_length=100)),
                ('tags', models.ManyToManyField(blank=True, to='relation_db.tag')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100)),
                ('international_passport', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='relation_db.person')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='chois_toure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='relation_db.person'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Documentcar',
        ),
        migrations.DeleteModel(
            name='NumberCar',
        ),
    ]
