# Generated by Django 6.0.1 on 2026-02-05 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0007_remove_numbercar_tags_remove_review_chois_car_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.CharField(max_length=100)),
                ('tourse', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registr', to='relation_db.person')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentPerson',
        ),
    ]
