# Generated by Django 6.0.1 on 2026-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0008_register_delete_documentperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(default='good toure', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='categories',
            field=models.ManyToManyField(blank=True, to='relation_db.touristcategory'),
        ),
    ]
