# Generated by Django 6.0.1 on 2026-02-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0009_touristcategory_alter_review_text_person_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='register',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='register',
            name='tourse',
        ),
        migrations.AddField(
            model_name='register',
            name='tour',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='relation_db.person'),
            preserve_default=False,
        ),
    ]
