# Generated by Django 6.0.1 on 2026-02-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proglang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите язык программирования')),
                ('description', models.TextField(verbose_name='Укажите описание языка')),
                ('experience', models.TextField(verbose_name='Напишите опыт работы с языками')),
                ('version', models.TextField(verbose_name='Укажите версию языка')),
                ('oficial_site', models.URLField(verbose_name='Укажите официальный сайт языка')),
                ('fails', models.FileField(upload_to='', verbose_name='Загрузите файл')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Укажите контактный email')),
                ('image', models.ImageField(upload_to='prog_lang/', verbose_name='Загрузите фото')),
                ('created_date_lang', models.PositiveBigIntegerField(blank=True, verbose_name='Укажите год создания языка программирования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'язык программирования',
                'verbose_name_plural': 'языки программирования',
            },
        ),
    ]
