# Generated by Django 6.0.1 on 2026-02-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proglang',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='proglang',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='proglang',
            name='fails',
        ),
        migrations.RemoveField(
            model_name='proglang',
            name='oficial_site',
        ),
        migrations.RemoveField(
            model_name='proglang',
            name='version',
        ),
    ]
