# Generated by Django 6.0.1 on 2026-02-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prog_lang', '0002_remove_proglang_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proglang',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
