# Generated by Django 6.0.1 on 2026-02-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('file', models.FileField(blank=True, null=True, upload_to='books_files/')),
                ('description', models.TextField(blank=True, null=True)),
                ('publisher_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('info_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
